version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz

homebrew_casks:
  - name: control
    binaries:
      - control
    repository:
      owner: StephanSchmidt
      name: homebrew-control
      token: "{{ .Env.HOMEBREW_CONTROL_TOKEN }}"
    homepage: https://github.com/StephanSchmidt/control
    description: Generate SVG diagrams from plain text

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
